"""modify Auth Users schema

Revision ID: 2a77674caa85
Revises: 9f69b2e12600
Create Date: 2024-09-02 14:31:48.432431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a77674caa85'
down_revision: Union[str, None] = '9f69b2e12600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authenticated_users', sa.Column('isLoggedIn', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'authenticated_users', ['id'])
    op.create_unique_constraint(None, 'cart_items', ['id'])
    op.create_unique_constraint(None, 'categories', ['id'])
    op.create_unique_constraint(None, 'order_items', ['id'])
    op.create_unique_constraint(None, 'orders', ['id'])
    op.create_unique_constraint(None, 'products', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'order_items', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'cart_items', type_='unique')
    op.drop_constraint(None, 'authenticated_users', type_='unique')
    op.drop_column('authenticated_users', 'isLoggedIn')
    # ### end Alembic commands ###
