"""update admins table

Revision ID: bc36a6da3af3
Revises: 928cb50ea577
Create Date: 2024-09-09 16:09:19.525509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc36a6da3af3'
down_revision: Union[str, None] = '928cb50ea577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admins', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admins', type_='unique')
    # ### end Alembic commands ###
